[tool.black]
line-length = 100
target-version = ['py312']
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["api_clients", "news_base", "io_manager"]
force_sort_within_sections = true
combine_as_imports = true
include_trailing_comma = true
multi_line_output = 3

[tool.mypy]
python_version = "3.12"
check_untyped_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
warn_unused_ignores = true
strict = true
