base_prompt: |
  As an AI investment advisor, recommend 2-3 investments for each of the following buckets.
  Only output ticker and official name. Prioritize ETFs available to European investors.
  Output each recommendation as: Bucket, Ticker, Official Name. No formatting, only the raw list.
bucket_file: investment_buckets.yaml
model: gpt-4o-mini